# Generated by Django 4.2.24 on 2025-09-29 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom checklist')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Checklist',
                'verbose_name_plural': 'Checklists',
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Élément')),
                ('required', models.BooleanField(default=False, verbose_name='Obligatoire')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nautical.checklist', verbose_name='Checklist')),
            ],
            options={
                'verbose_name': 'Élément de checklist',
                'verbose_name_plural': 'Éléments de checklist',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Nom / Prénom')),
                ('role', models.CharField(choices=[('Skipper', 'Skipper'), ('Équipier', 'Équipier'), ('Invité', 'Invité')], default='Équipier', max_length=30, verbose_name='Rôle')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='Téléphone / Email')),
                ('has_license', models.BooleanField(default=False, verbose_name='Licence FFV / Assur.')),
                ('notes', models.TextField(blank=True, verbose_name='Remarques')),
            ],
            options={
                'verbose_name': "Membre d'équipage",
                'verbose_name_plural': 'Équipage',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='LogbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Date de départ')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Date d’arrivée')),
                ('departure_port', models.CharField(max_length=120, verbose_name='Port / Mouillage départ')),
                ('arrival_port', models.CharField(blank=True, max_length=120, verbose_name='Port / Mouillage arrivée')),
                ('start_position', models.CharField(blank=True, help_text="Ex: 17°32'S / 149°34'W", max_length=80, verbose_name='Position départ')),
                ('end_position', models.CharField(blank=True, max_length=80, verbose_name='Position arrivée')),
                ('distance_nm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Distance parcourue (NM)')),
                ('avg_speed_kn', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Vitesse moyenne (kn)')),
                ('weather', models.CharField(blank=True, max_length=120, verbose_name='Conditions météo')),
                ('wind', models.CharField(blank=True, max_length=80, verbose_name='Vent (dir/force)')),
                ('sea_state', models.CharField(blank=True, max_length=80, verbose_name='État de la mer / houle')),
                ('tide_current', models.CharField(blank=True, max_length=80, verbose_name='Marée / Courant')),
                ('avg_course', models.IntegerField(blank=True, null=True, verbose_name='Cap moyen suivi')),
                ('engine_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Moteur – heures de marche')),
                ('fuel_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Carburant consommé (L)')),
                ('notes', models.TextField(blank=True, verbose_name='Incidents / Notes')),
                ('photos_url', models.URLField(blank=True, verbose_name='Photos / Vidéos (URL)')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='voyages/covers/', verbose_name='Photo de couverture')),
                ('crew', models.ManyToManyField(blank=True, related_name='voyages', to='nautical.crewmember', verbose_name='Équipage')),
            ],
            options={
                'verbose_name': 'Voyage',
                'verbose_name_plural': 'Logbook (Voyages)',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('photo', 'Photo'), ('video', 'Vidéo')], default='photo', max_length=10, verbose_name='Type')),
                ('image', models.ImageField(blank=True, null=True, upload_to='voyages/photos/', verbose_name='Image')),
                ('file', models.FileField(blank=True, null=True, upload_to='voyages/files/', verbose_name='Fichier')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='nautical.logbookentry', verbose_name='Voyage')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Médias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date intervention')),
                ('equipment', models.CharField(choices=[('Moteur', 'Moteur'), ('Gréement', 'Gréement'), ('Électronique', 'Électronique'), ('Voiles', 'Voiles'), ('Coque', 'Coque'), ('Divers', 'Divers')], default='Divers', max_length=30, verbose_name='Équipement concerné')),
                ('description', models.TextField(verbose_name='Description')),
                ('cost_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Coût (€)')),
                ('engine_hours_at_time', models.IntegerField(blank=True, null=True, verbose_name='Heure moteur liée')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='Prochaine échéance')),
                ('voyage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance', to='nautical.logbookentry', verbose_name='Lien voyage')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenance',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='nautical.checklist', verbose_name='Checklist')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_runs', to='nautical.logbookentry', verbose_name='Voyage')),
            ],
            options={
                'verbose_name': 'Checklist (instance)',
                'verbose_name_plural': 'Checklists (instances)',
                'unique_together': {('checklist', 'voyage')},
            },
        ),
        migrations.CreateModel(
            name='ChecklistItemRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False, verbose_name='Coché')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Note')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='nautical.checklistitem', verbose_name='Élément')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_runs', to='nautical.checklistrun', verbose_name='Instance')),
            ],
            options={
                'verbose_name': 'Élément coché',
                'verbose_name_plural': 'Éléments cochés',
                'unique_together': {('run', 'item')},
            },
        ),
    ]
