# Generated by Django 4.2.24 on 2025-10-01 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom du consommable')),
                ('origin', models.CharField(choices=[('moteur', 'Moteur'), ('electricite', 'Électricité'), ('electronique', 'Électronique'), ('accastillage', 'Accastillage'), ('navigation', 'Navigation'), ('osmoseur', 'Osmoseur'), ('divers', 'Divers')], default='divers', max_length=20, verbose_name='Origine')),
                ('reference', models.CharField(blank=True, max_length=150, verbose_name='Référence')),
                ('image', models.FileField(blank=True, help_text='Formats acceptés : jpg, jpeg, png, dng', null=True, upload_to='consommables/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'dng'])], verbose_name='Image (jpg/jpeg/png) ou DNG')),
                ('remark', models.TextField(blank=True, verbose_name='Remarque')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantité')),
            ],
            options={
                'verbose_name': 'Consommable',
                'verbose_name_plural': 'Consommables',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='consumable',
            constraint=models.UniqueConstraint(fields=('name', 'origin', 'reference'), name='uniq_consumable_name_origin_ref'),
        ),
    ]
