# Generated by Django 4.2.24 on 2025-10-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautical', '0002_consumable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumable',
            name='price_eur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Prix (€)'),
        ),
    ]
