# Generated by Django 4.2.24 on 2025-10-04 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nautical', '0003_checklistitem_action'),
        ('nautical', '0003_consumable_price_eur'),
    ]

    operations = [
    ]
