# Generated by Django 4.2.24 on 2025-10-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautical', '0004_merge_20251003_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chronology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Heure')),
                ('description', models.TextField(verbose_name='Description')),
                ('action_realisee', models.TextField(blank=True, verbose_name='Action réalisée')),
                ('performer', models.CharField(choices=[('Terry', 'Terry'), ('Jean-Ariel', 'Jean-Ariel')], default='Terry', max_length=40, verbose_name='Réalisé par')),
            ],
            options={
                'verbose_name': 'Chronologie',
                'verbose_name_plural': 'Chronologie',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
