# Generated by Django 4.2.24 on 2025-10-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautical', '0006_add_latlng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbookentry',
            name='end_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude arrivée'),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='end_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude arrivée'),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='start_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude départ'),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='start_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude départ'),
        ),
    ]
