# Generated by Django 4.2.24 on 2025-10-06 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nautical', '0009_add_duration_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoyageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Date et heure')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('description', models.TextField(verbose_name="Détail de l'événement")),
                ('weather', models.CharField(blank=True, max_length=120, verbose_name='Conditions météo')),
                ('notes', models.TextField(blank=True, verbose_name='Remarques')),
                ('distance_from_prev_nm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Distance depuis précédent (NM)')),
                ('elapsed_hours_since_prev', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temps écoulé depuis précédent (heures)')),
                ('avg_speed_since_prev_kn', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Vitesse moyenne depuis précédent (kn)')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='nautical.logbookentry', verbose_name='Voyage')),
            ],
            options={
                'verbose_name': 'Événement de voyage',
                'verbose_name_plural': 'Événements de voyage',
                'ordering': ['-timestamp'],
            },
        ),
    ]
