# Generated by Django 4.2.24 on 2025-10-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautical', '0012_logentry_voyagecrewmember_voyagelog_weathercondition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyagelog',
            name='sujet_voyage',
            field=models.CharField(default='', help_text='Ex: Séjour à Moorea, Visite des Tuamotu', max_length=200, verbose_name='Sujet du voyage'),
        ),
    ]
