# Generated by Django 4.2.24 on 2025-10-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautical', '0014_crewmembernew_voyagelognew_weatherconditionnew_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='crewmembernew',
            index=models.Index(fields=['voyage', 'role', 'nom'], name='nautical_cr_voyage__7cecec_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentnew',
            index=models.Index(fields=['voyage', 'datetime'], name='nautical_in_voyage__afb46d_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentnew',
            index=models.Index(fields=['type_incident'], name='nautical_in_type_in_12643d_idx'),
        ),
        migrations.AddIndex(
            model_name='logentrynew',
            index=models.Index(fields=['voyage', 'date', 'heure'], name='nautical_lo_voyage__b91618_idx'),
        ),
        migrations.AddIndex(
            model_name='logentrynew',
            index=models.Index(fields=['date', 'heure'], name='nautical_lo_date_e17829_idx'),
        ),
        migrations.AddIndex(
            model_name='securityinstruction',
            index=models.Index(fields=['voyage', 'priorite'], name='nautical_se_voyage__0538ba_idx'),
        ),
        migrations.AddIndex(
            model_name='voyagelognew',
            index=models.Index(fields=['statut', 'date_debut'], name='nautical_vo_statut_c9a85f_idx'),
        ),
        migrations.AddIndex(
            model_name='voyagelognew',
            index=models.Index(fields=['date_debut'], name='nautical_vo_date_de_539dc8_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherconditionnew',
            index=models.Index(fields=['voyage', 'datetime'], name='nautical_we_voyage__5d389a_idx'),
        ),
        migrations.AddConstraint(
            model_name='voyagelognew',
            constraint=models.CheckConstraint(check=models.Q(('date_fin__isnull', True), ('date_fin__gte', models.F('date_debut')), _connector='OR'), name='voyage_date_fin_after_debut_new'),
        ),
    ]
