# Generated by Django 4.2.24 on 2025-10-13 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nautical', '0015_crewmembernew_nautical_cr_voyage__7cecec_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoyagePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='voyages/photos/%Y/%m/', verbose_name='Photo')),
                ('type_photo', models.CharField(choices=[('header', "Photo d'en-tête"), ('gallery', 'Photo de galerie')], default='gallery', max_length=20, verbose_name='Type de photo')),
                ('titre', models.CharField(blank=True, max_length=200, verbose_name='Titre de la photo')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_prise', models.DateField(blank=True, null=True, verbose_name='Date de prise de vue')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taille_fichier', models.PositiveIntegerField(blank=True, null=True, verbose_name='Taille du fichier')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='nautical.voyagelognew')),
            ],
            options={
                'verbose_name': 'Photo de voyage',
                'verbose_name_plural': 'Photos de voyage',
                'ordering': ['type_photo', 'ordre', 'created_at'],
                'indexes': [models.Index(fields=['voyage', 'type_photo'], name='nautical_vo_voyage__bbfca0_idx'), models.Index(fields=['voyage', 'ordre'], name='nautical_vo_voyage__1eff32_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='voyagephoto',
            constraint=models.UniqueConstraint(condition=models.Q(('type_photo', 'header')), fields=('voyage',), name='unique_header_photo_per_voyage'),
        ),
    ]
