name: Build frontend and commit

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Node / npm versions
        run: |
          node --version
          npm --version || true

      - name: Install dependencies (verbose)
        run: |
          cd frontend
          npm install --verbose

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Commit build
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add static/frontend -A || true
          git commit -m "chore(ci): build frontend [skip ci]" || echo "no changes to commit"
          git push origin HEAD:main
